### ISSUE TITLE
Change yapf requirement back to strict match?

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#525]
In #513, the `yapf` requirement was changed to `~=0.29`  - which I didn't notice when reviewing 😅

I think in the case of `yapf`, the requirement should actually be a strict one. The problem with the compatible release clause is that formatting can change between different versions of `yapf`, which can lead to:
- CI installing a newer version than the developer, and subsequently failing the pre-commit step
- a "ping-pong" of formatting between different developers that don't have the same version installed

**Comment by sphuber** [comment]
The same holds for other pre-commit tools, like `pylint` no? In some other projects I have been preferring remote dependency instead of local, i.e.:
```
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        args: ['-i']
```
This would solve the issue as well, correct? If you are happy with that, I will make a PR where I also do some other pre-commit things I wanted to do
